version: '3.1'

services:

  postgres:
    image: postgres:11
    ports: 
      - 5050:5432
    container_name: postgrespls
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
